### PR TITLE
Define `WRAPPER` in straight Python

### PR DESCRIPTION
**Pull request by jakirkham**
Seemed subjectively nicer to me. :)

### CODE REVIEW

**Comment by hanslovsky** [comment]
Unfortunately I do not have a mac to confirm this works. Will check when I get hands on a mac.

**Comment by jakirkham** [comment]
No worries. Feel free to check. FWIW this is what we were using earlier.

Thanks again for you help BTW. :)

**Comment by hanslovsky** [comment]
What worries me a little is that the `$()` has gone. So instead of the output of the command the command is stored.

**Comment by jakirkham** [comment]
Yep, you're right. That was a typo. Pushed a fix.

**Pull request merged**
